export const
    // JSON_URL = "data.json",
    JSON_URL = "/progress-dashboard",
    P2P_MANUAL_URL = "https://docs.google.com/document/d/1fKcyyvM8P7wo2zB3sfeQRcMVsHWYsPknH_rRneBwDrI/edit", // add "?usp=sharing" to read
    FEEDBACK_FORM_URL = "https://docs.google.com/forms/d/e/1FAIpQLSe9pj_O5ZBncv6yfTlAjPHPC8Ma8gt1pfzu3o3j5ofz9e0n0g/viewform",
    A_MATERIALS_URL = "/provide-data?directory=a&filename=",
    B_MATERIALS_URL = "/provide-data?directory=b&filename=",
    REDIRECT_URL = "/redirect-to?url=",
    ADMIN_MAIL = "p2p@programming.kr.ua",
    AVATARS_PATH = "/images/avatars/",
    P2P_VIDEOS_PATH = '/p2p-videos?file=',
    HOMEWORKS_PATH = "/homeworks/",
    DAYS_TO_DO_HOMEWORK = 9,
    REVIEW_1_DURATION = 4,
    REVIEW_2_DURATION = 3,
    NOTIFICATION_FIRST_MEETING = "Сегодня понедельник и мы встречаемся на школе в <strong>19:00</strong> для обсуждения организационных вопросов с нашей командой",
    NOTIFICATION_THEORY_MEETING = "Сегодня понедельник, и мы встречаемся на школе на <strong>18:30</strong> на теоретическое занятие, вопросы &mdash; THEORY_QUESTIONS_LINK",
    NOTIFICATION_FREEZED = "Вы не приняли участие в ревью, поэтому получили +1 предупреждение. Попробуйте опять на следующей неделе.",
    NOTIFICATION_TG_EMPTY = "Мы заметили, что вы не заполнили поля телефона и/или телеграмма :( Пожалуйста, добавьте данные, иначе мы не сможем пригласить вас в наши группы. Проверьте, что указанный вами номер привязан к указанному телеграмм-нейму",
    NOTIFICATION_CODE_EMPTY = 'Залейте код сегодня и подтвердите участие в ревью, если вы до сих пор этого не сделали (проскролльте вниз и поставьте галочку).',
    DEADLINE_TIME = '23:59:59',
    FEEDBACK_FORM1_START_TIME = '22:00:00',
    FEEDBACK_FORM2_START_TIME = '23:00:00'
